In [ ]:
!pip install TikTokApi
!playwright install
!playwright install-deps

Collecting TikTokApi
  Downloading tiktokapi-7.3.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests<3.0,>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from TikTokApi) (2.32.4)
Collecting playwright<2.0,>=1.36.0 (from TikTokApi)
  Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: httpx<1.0,>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from TikTokApi) (0.28.1)
Collecting proxyproviders<0.3.0,>=0.2.1 (from TikTokApi)
  Downloading proxyproviders-0.2.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.27.0->TikTokApi) (0.16.0)
Collecting pyee<14,>=13 (from playwright<2.0,>=1.36.0->TikTokApi)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from playwright<2.0,>=1.36.0->TikTokApi) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31.0->TikTokApi) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31.0->TikTokApi) (2.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from pyee<14,>=13->playwright<2.0,>=1.36.0->TikTokApi) (4.15.0)
Downloading tiktokapi-7.3.1-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 3.3 MB/s eta 0:00:00
Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 24.0 MB/s eta 0:00:00
Downloading proxyproviders-0.2.1-py3-none-any.whl (16 kB)
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: pyee, proxyproviders, playwright, TikTokApi
Successfully installed TikTokApi-7.3.1 playwright-1.58.0 proxyproviders-0.2.1 pyee-13.0.1
Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-linux64.zip
(node:2163) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
167.3 MiB [] 0% 0.0s167.3 MiB [] 0% 41.4s167.3 MiB [] 0% 17.5s167.3 MiB [] 0% 14.5s167.3 MiB [] 0% 11.7s167.3 MiB [] 1% 5.8s167.3 MiB [] 2% 4.6s167.3 MiB [] 2% 3.8s167.3 MiB [] 3% 3.5s167.3 MiB [] 3% 3.6s167.3 MiB [] 4% 3.5s167.3 MiB [] 5% 3.1s167.3 MiB [] 6% 2.8s167.3 MiB [] 7% 2.6s167.3 MiB [] 8% 2.5s167.3 MiB [] 9% 2.4s167.3 MiB [] 10% 2.3s167.3 MiB [] 11% 2.2s167.3 MiB [] 12% 2.1s167.3 MiB [] 13% 2.0s167.3 MiB [] 14% 2.0s167.3 MiB [] 15% 2.0s167.3 MiB [] 16% 2.0s167.3 MiB [] 17% 2.0s167.3 MiB [] 17% 1.9s167.3 MiB [] 18% 1.9s167.3 MiB [] 19% 1.9s167.3 MiB [] 20% 1.8s167.3 MiB [] 21% 1.8s167.3 MiB [] 22% 1.8s167.3 MiB [] 23% 1.7s167.3 MiB [] 24% 1.6s167.3 MiB [] 25% 1.6s167.3 MiB [] 27% 1.5s167.3 MiB [] 28% 1.5s167.3 MiB [] 29% 1.4s167.3 MiB [] 30% 1.4s167.3 MiB [] 31% 1.4s167.3 MiB [] 33% 1.3s167.3 MiB [] 34% 1.3s167.3 MiB [] 35% 1.3s167.3 MiB [] 36% 1.2s167.3 MiB [] 37% 1.2s167.3 MiB [] 39% 1.1s167.3 MiB [] 40% 1.1s167.3 MiB [] 41% 1.1s167.3 MiB [] 42% 1.1s167.3 MiB [] 43% 1.0s167.3 MiB [] 44% 1.0s167.3 MiB [] 45% 1.0s167.3 MiB [] 46% 1.0s167.3 MiB [] 47% 1.0s167.3 MiB [] 48% 0.9s167.3 MiB [] 49% 0.9s167.3 MiB [] 50% 0.9s167.3 MiB [] 52% 0.9s167.3 MiB [] 53% 0.9s167.3 MiB [] 54% 0.8s167.3 MiB [] 55% 0.8s167.3 MiB [] 56% 0.8s167.3 MiB [] 58% 0.7s167.3 MiB [] 59% 0.7s167.3 MiB [] 60% 0.7s167.3 MiB [] 62% 0.7s167.3 MiB [] 63% 0.6s167.3 MiB [] 64% 0.6s167.3 MiB [] 65% 0.6s167.3 MiB [] 66% 0.6s167.3 MiB [] 67% 0.6s167.3 MiB [] 68% 0.5s167.3 MiB [] 69% 0.5s167.3 MiB [] 70% 0.5s167.3 MiB [] 71% 0.5s167.3 MiB [] 72% 0.5s167.3 MiB [] 74% 0.5s167.3 MiB [] 75% 0.4s167.3 MiB [] 76% 0.4s167.3 MiB [] 77% 0.4s167.3 MiB [] 79% 0.4s167.3 MiB [] 80% 0.3s167.3 MiB [] 81% 0.3s167.3 MiB [] 82% 0.3s167.3 MiB [] 83% 0.3s167.3 MiB [] 84% 0.3s167.3 MiB [] 85% 0.2s167.3 MiB [] 86% 0.2s167.3 MiB [] 88% 0.2s167.3 MiB [] 89% 0.2s167.3 MiB [] 91% 0.2s167.3 MiB [] 92% 0.1s167.3 MiB [] 93% 0.1s167.3 MiB [] 95% 0.1s167.3 MiB [] 96% 0.1s167.3 MiB [] 97% 0.0s167.3 MiB [] 98% 0.0s167.3 MiB [] 99% 0.0s167.3 MiB [] 100% 0.0s
Chrome for Testing 145.0.7632.6 (playwright chromium v1208) downloaded to /root/.cache/ms-playwright/chromium-1208
Downloading Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-headless-shell-linux64.zip
(node:2208) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
110.9 MiB [] 0% 0.0s110.9 MiB [] 0% 34.3s110.9 MiB [] 0% 21.0s110.9 MiB [] 0% 15.8s110.9 MiB [] 0% 13.6s110.9 MiB [] 0% 11.8s110.9 MiB [] 1% 8.2s110.9 MiB [] 1% 6.0s110.9 MiB [] 2% 4.6s110.9 MiB [] 3% 3.7s110.9 MiB [] 4% 4.2s110.9 MiB [] 4% 4.0s110.9 MiB [] 5% 3.4s110.9 MiB [] 6% 3.2s110.9 MiB [] 7% 2.9s110.9 MiB [] 8% 2.8s110.9 MiB [] 9% 2.7s110.9 MiB [] 10% 2.5s110.9 MiB [] 11% 2.4s110.9 MiB [] 12% 2.3s110.9 MiB [] 13% 2.1s110.9 MiB [] 15% 1.9s110.9 MiB [] 17% 1.8s110.9 MiB [] 18% 1.9s110.9 MiB [] 18% 2.0s110.9 MiB [] 18% 2.1s110.9 MiB [] 18% 2.2s110.9 MiB [] 19% 2.1s110.9 MiB [] 20% 2.0s110.9 MiB [] 21% 2.0s110.9 MiB [] 22% 2.0s110.9 MiB [] 23% 1.9s110.9 MiB [] 24% 1.9s110.9 MiB [] 26% 1.8s110.9 MiB [] 27% 1.7s110.9 MiB [] 28% 1.7s110.9 MiB [] 29% 1.7s110.9 MiB [] 30% 1.6s110.9 MiB [] 31% 1.6s110.9 MiB [] 32% 1.5s110.9 MiB [] 34% 1.5s110.9 MiB [] 35% 1.4s110.9 MiB [] 37% 1.4s110.9 MiB [] 38% 1.3s110.9 MiB [] 39% 1.3s110.9 MiB [] 40% 1.2s110.9 MiB [] 41% 1.2s110.9 MiB [] 42% 1.2s110.9 MiB [] 43% 1.2s110.9 MiB [] 44% 1.1s110.9 MiB [] 46% 1.1s110.9 MiB [] 47% 1.0s110.9 MiB [] 48% 1.0s110.9 MiB [] 50% 1.0s110.9 MiB [] 51% 0.9s110.9 MiB [] 52% 0.9s110.9 MiB [] 53% 0.9s110.9 MiB [] 54% 0.9s110.9 MiB [] 55% 0.8s110.9 MiB [] 57% 0.8s110.9 MiB [] 58% 0.8s110.9 MiB [] 59% 0.7s110.9 MiB [] 60% 0.7s110.9 MiB [] 61% 0.7s110.9 MiB [] 62% 0.7s110.9 MiB [] 63% 0.7s110.9 MiB [] 65% 0.6s110.9 MiB [] 66% 0.6s110.9 MiB [] 67% 0.6s110.9 MiB [] 68% 0.6s110.9 MiB [] 69% 0.6s110.9 MiB [] 70% 0.6s110.9 MiB [] 71% 0.5s110.9 MiB [] 72% 0.5s110.9 MiB [] 73% 0.5s110.9 MiB [] 75% 0.5s110.9 MiB [] 76% 0.4s110.9 MiB [] 78% 0.4s110.9 MiB [] 79% 0.4s110.9 MiB [] 80% 0.3s110.9 MiB [] 82% 0.3s110.9 MiB [] 83% 0.3s110.9 MiB [] 84% 0.3s110.9 MiB [] 85% 0.2s110.9 MiB [] 87% 0.2s110.9 MiB [] 88% 0.2s110.9 MiB [] 90% 0.2s110.9 MiB [] 91% 0.1s110.9 MiB [] 93% 0.1s110.9 MiB [] 94% 0.1s110.9 MiB [] 95% 0.1s110.9 MiB [] 97% 0.0s110.9 MiB [] 98% 0.0s110.9 MiB [] 100% 0.0s
Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1208
Downloading Firefox 146.0.1 (playwright firefox v1509) from https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1509/firefox-ubuntu-22.04.zip
(node:2243) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
99.5 MiB [] 0% 0.0s99.5 MiB [] 0% 7.0s99.5 MiB [] 0% 3.9s99.5 MiB [] 1% 3.1s99.5 MiB [] 2% 2.7s99.5 MiB [] 3% 2.2s99.5 MiB [] 4% 1.8s99.5 MiB [] 6% 1.7s99.5 MiB [] 6% 1.9s99.5 MiB [] 8% 1.6s99.5 MiB [] 10% 1.4s99.5 MiB [] 12% 1.3s99.5 MiB [] 14% 1.2s99.5 MiB [] 15% 1.2s99.5 MiB [] 16% 1.2s99.5 MiB [] 18% 1.1s99.5 MiB [] 19% 1.1s99.5 MiB [] 20% 1.1s99.5 MiB [] 21% 1.1s99.5 MiB [] 22% 1.1s99.5 MiB [] 23% 1.1s99.5 MiB [] 24% 1.1s99.5 MiB [] 25% 1.1s99.5 MiB [] 26% 1.1s99.5 MiB [] 28% 1.0s99.5 MiB [] 30% 1.0s99.5 MiB [] 31% 0.9s99.5 MiB [] 32% 1.0s99.5 MiB [] 33% 0.9s99.5 MiB [] 34% 0.9s99.5 MiB [] 36% 0.9s99.5 MiB [] 37% 0.9s99.5 MiB [] 38% 0.9s99.5 MiB [] 40% 0.9s99.5 MiB [] 42% 0.8s99.5 MiB [] 43% 0.8s99.5 MiB [] 44% 0.8s99.5 MiB [] 45% 0.8s99.5 MiB [] 47% 0.8s99.5 MiB [] 48% 0.7s99.5 MiB [] 49% 0.7s99.5 MiB [] 50% 0.7s99.5 MiB [] 52% 0.7s99.5 MiB [] 54% 0.6s99.5 MiB [] 56% 0.6s99.5 MiB [] 58% 0.6s99.5 MiB [] 60% 0.5s99.5 MiB [] 62% 0.5s99.5 MiB [] 63% 0.5s99.5 MiB [] 65% 0.5s99.5 MiB [] 66% 0.4s99.5 MiB [] 68% 0.4s99.5 MiB [] 70% 0.4s99.5 MiB [] 72% 0.4s99.5 MiB [] 73% 0.3s99.5 MiB [] 74% 0.3s99.5 MiB [] 76% 0.3s99.5 MiB [] 78% 0.3s99.5 MiB [] 80% 0.3s99.5 MiB [] 81% 0.2s99.5 MiB [] 82% 0.2s99.5 MiB [] 83% 0.2s99.5 MiB [] 84% 0.2s99.5 MiB [] 86% 0.2s99.5 MiB [] 88% 0.2s99.5 MiB [] 90% 0.1s99.5 MiB [] 92% 0.1s99.5 MiB [] 94% 0.1s99.5 MiB [] 95% 0.1s99.5 MiB [] 96% 0.0s99.5 MiB [] 98% 0.0s99.5 MiB [] 99% 0.0s99.5 MiB [] 100% 0.0s
Firefox 146.0.1 (playwright firefox v1509) downloaded to /root/.cache/ms-playwright/firefox-1509
Downloading WebKit 26.0 (playwright webkit v2248) from https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2248/webkit-ubuntu-22.04.zip
(node:2278) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
99.4 MiB [] 0% 0.0s99.4 MiB [] 0% 5.6s99.4 MiB [] 1% 3.1s99.4 MiB [] 1% 2.5s99.4 MiB [] 2% 2.1s99.4 MiB [] 4% 1.7s99.4 MiB [] 5% 1.5s99.4 MiB [] 6% 1.6s99.4 MiB [] 7% 1.6s99.4 MiB [] 9% 1.5s99.4 MiB [] 10% 1.4s99.4 MiB [] 12% 1.5s99.4 MiB [] 14% 1.3s99.4 MiB [] 14% 1.4s99.4 MiB [] 16% 1.3s99.4 MiB [] 18% 1.3s99.4 MiB [] 19% 1.2s99.4 MiB [] 21% 1.2s99.4 MiB [] 22% 1.2s99.4 MiB [] 24% 1.1s99.4 MiB [] 26% 1.1s99.4 MiB [] 27% 1.0s99.4 MiB [] 28% 1.0s99.4 MiB [] 29% 1.0s99.4 MiB [] 31% 1.0s99.4 MiB [] 33% 0.9s99.4 MiB [] 34% 0.9s99.4 MiB [] 36% 0.9s99.4 MiB [] 37% 0.9s99.4 MiB [] 38% 0.9s99.4 MiB [] 39% 0.9s99.4 MiB [] 40% 0.9s99.4 MiB [] 42% 0.9s99.4 MiB [] 43% 0.9s99.4 MiB [] 45% 0.8s99.4 MiB [] 47% 0.8s99.4 MiB [] 48% 0.8s99.4 MiB [] 50% 0.7s99.4 MiB [] 52% 0.7s99.4 MiB [] 54% 0.7s99.4 MiB [] 56% 0.7s99.4 MiB [] 58% 0.6s99.4 MiB [] 60% 0.6s99.4 MiB [] 61% 0.6s99.4 MiB [] 62% 0.6s99.4 MiB [] 63% 0.5s99.4 MiB [] 66% 0.5s99.4 MiB [] 68% 0.5s99.4 MiB [] 71% 0.4s99.4 MiB [] 73% 0.4s99.4 MiB [] 74% 0.4s99.4 MiB [] 76% 0.3s99.4 MiB [] 77% 0.3s99.4 MiB [] 78% 0.3s99.4 MiB [] 79% 0.3s99.4 MiB [] 80% 0.3s99.4 MiB [] 81% 0.3s99.4 MiB [] 83% 0.2s99.4 MiB [] 84% 0.2s99.4 MiB [] 86% 0.2s99.4 MiB [] 89% 0.2s99.4 MiB [] 91% 0.1s99.4 MiB [] 93% 0.1s99.4 MiB [] 95% 0.1s99.4 MiB [] 96% 0.0s99.4 MiB [] 97% 0.0s99.4 MiB [] 99% 0.0s99.4 MiB [] 100% 0.0s
WebKit 26.0 (playwright webkit v2248) downloaded to /root/.cache/ms-playwright/webkit-2248
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
(node:2309) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
2.3 MiB [] 0% 0.0s2.3 MiB [] 9% 0.2s2.3 MiB [] 36% 0.1s2.3 MiB [] 71% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Playwright Host validation warning:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     playwright install-deps                          ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     apt-get install libxcomposite1\                  ║
║         libgtk-3-0\                                  ║
║         libatk1.0-0                                  ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/dependencies.js:269:9)
    at async Registry._validateHostRequirements (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:991:14)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:1113:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/server/registry/index.js:1102:7)
    at async i.<anonymous> (/usr/local/lib/python3.12/dist-packages/playwright/driver/package/lib/cli/program.js:174:7)
Installing dependencies...
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.2 kB]
Get:8 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,810 kB]
Get:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,120 kB]
Get:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [39.2 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,613 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,301 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,877 kB]
Get:20 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Get:21 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,921 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,780 kB]
Get:23 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,652 kB]
Fetched 37.8 MB in 4s (9,903 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-liberation is already the newest version (1:1.07.4-11).
libcairo-gobject2 is already the newest version (1.16.0-5ubuntu2).
libcairo-gobject2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2).
libcairo2 set to manually installed.
libegl1 is already the newest version (1.4.0-1).
libepoxy0 is already the newest version (1.5.10-1).
libepoxy0 set to manually installed.
libevent-2.1-7 is already the newest version (2.1.12-stable-1build3).
libevent-2.1-7 set to manually installed.
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libgles2 is already the newest version (1.4.0-1).
libglx0 is already the newest version (1.4.0-1).
libglx0 set to manually installed.
libicu70 is already the newest version (70.1-2).
libicu70 set to manually installed.
libjpeg-turbo8 is already the newest version (2.1.2-0ubuntu1).
libjpeg-turbo8 set to manually installed.
liblcms2-2 is already the newest version (2.12~rc1-2build2).
liblcms2-2 set to manually installed.
libopengl0 is already the newest version (1.4.0-1).
libopus0 is already the newest version (1.3.1-0.1build2).
libopus0 set to manually installed.
libxcb-shm0 is already the newest version (1.14-3ubuntu3).
libxcb-shm0 set to manually installed.
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcb1 set to manually installed.
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxcursor1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build1).
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxi6 is already the newest version (2:1.8-1build1).
libxi6 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libxrender1 is already the newest version (1:0.9.10-1build4).
libx264-163 is already the newest version (2:0.163.3060+git5db6aa6-2build1).
libx264-163 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libcups2 set to manually installed.
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libfreetype6 is already the newest version (2.11.1+dfsg-1ubuntu0.3).
libfreetype6 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libgdk-pixbuf-2.0-0 is already the newest version (2.42.8+dfsg-1ubuntu0.4).
libgdk-pixbuf-2.0-0 set to manually installed.
libgstreamer1.0-0 is already the newest version (1.20.3-0ubuntu1.1).
libgstreamer1.0-0 set to manually installed.
libgtk-4-1 is already the newest version (4.6.9+ds-0ubuntu0.22.04.2).
libgtk-4-1 set to manually installed.
libharfbuzz0b is already the newest version (2.7.4-1ubuntu3.2).
libharfbuzz0b set to manually installed.
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnspr4 set to manually installed.
libopenjp2-7 is already the newest version (2.4.0-6ubuntu0.4).
libopenjp2-7 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-client0 set to manually installed.
libwayland-egl1 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-egl1 set to manually installed.
libwayland-server0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-server0 set to manually installed.

In [ ]:
import asyncio
from TikTokApi import TikTokApi
import pandas as pd
from google.colab import files
import os

async def crawl_and_export_csv(keyword, video_count=10):
    hashtag_name = keyword.replace(" ", "").replace("#", "")
    print(f"Đang tìm kiếm với hashtag: #{hashtag_name}")

    api = TikTokApi()
    video_data_list = []

    try:
        # Khởi tạo session
        await api.create_sessions(
            num_sessions=1,
            sleep_after=10,
            browser='webkit',
            headless=True
        )

        tag = api.hashtag(name=hashtag_name)
        count = 0
        print("Đang lấy dữ liệu... (vui lòng chờ)")

        async for video in tag.videos(count=video_count):
            v_info = video.as_dict
            author = v_info.get("author", {}).get("uniqueId")
            v_id = v_info.get("id")
            stats = v_info.get("stats", {})

            # Thu thập các trường thông tin quan trọng
            record = {
                "Video ID": v_id,
                "URL": f"https://www.tiktok.com/@{author}/video/{v_id}",
                "Tác giả": author,
                "Mô tả": v_info.get("desc", ""),
                "Lượt tim": stats.get("diggCount", 0),
                "Lượt xem": stats.get("playCount", 0),
                "Lượt chia sẻ": stats.get("shareCount", 0),
                "Lượt bình luận": stats.get("commentCount", 0)
            }
            video_data_list.append(record)

            print(f"- Đã lấy video {count + 1}: {record['URL']}")

            count += 1
            if count >= video_count:
                break

        if video_data_list:
            # Tạo DataFrame và xuất CSV
            df = pd.DataFrame(video_data_list)
            csv_filename = f"tiktok_data_{hashtag_name}.csv"
            # utf-8-sig giúp Excel hiển thị đúng tiếng Việt
            df.to_csv(csv_filename, index=False, encoding='utf-8-sig')

            print(f"\n[XONG] Đã thu thập {len(video_data_list)} video.")
            print(f"Đang tự động tải file '{csv_filename}' xuống...")
            files.download(csv_filename)
        else:
            print("\n[THÔNG BÁO] Không có dữ liệu để xuất file (có thể do bị chặn IP).")

    except Exception as e:
        print(f"Lỗi: {e}")
    finally:
        await api.close_sessions()

# --- CẤU HÌNH CHẠY ---
keyword = "xe hơi" # @param {type:"string"}
video_limit = 20 # @param {type:"integer"}

await crawl_and_export_csv(keyword, video_count=video_limit)

Đang tìm kiếm với hashtag: #xehơi
Đang lấy dữ liệu... (vui lòng chờ)
- Đã lấy video 1: https://www.tiktok.com/@zoom6car/video/7613253519184842005
- Đã lấy video 2: https://www.tiktok.com/@anhchuxuongdeptrai/video/7612659344768896264
- Đã lấy video 3: https://www.tiktok.com/@vungocthanhh/video/7353136888313679124
- Đã lấy video 4: https://www.tiktok.com/@quenha.6/video/7608966011928317215
- Đã lấy video 5: https://www.tiktok.com/@cuongnuocmy/video/7427307108728687915
- Đã lấy video 6: https://www.tiktok.com/@cuongnuocmy/video/7377548592749317418
- Đã lấy video 7: https://www.tiktok.com/@autocarclub/video/7275932066582154503
- Đã lấy video 8: https://www.tiktok.com/@thaidacde1999/video/7544259066764479762
- Đã lấy video 9: https://www.tiktok.com/@sieuxe.360/video/7612687977428339975
- Đã lấy video 10: https://www.tiktok.com/@gatgu_channel/video/7456391235574517008
- Đã lấy video 11: https://www.tiktok.com/@chuyen_ve_oto/video/7605222950781898004
- Đã lấy video 12: https://www.tiktok.com/@bnkn_tv2/video/7612907193507138834
- Đã lấy video 13: https://www.tiktok.com/@phukienxehoiplus/video/7355697971394088210
- Đã lấy video 14: https://www.tiktok.com/@hoarousy/video/7374754620641430792
- Đã lấy video 15: https://www.tiktok.com/@alexnguye/video/7306514112425544961
- Đã lấy video 16: https://www.tiktok.com/@thuthuyyy99neee/video/7612772155197050132
- Đã lấy video 17: https://www.tiktok.com/@hcar.vn/video/7612854832122055944
- Đã lấy video 18: https://www.tiktok.com/@vo_tran_quoc_trung/video/7613083016071597333
- Đã lấy video 19: https://www.tiktok.com/@hiucar2010/video/7412855572627934470
- Đã lấy video 20: https://www.tiktok.com/@memoe2609_/video/7584388044275453204

[XONG] Đã thu thập 20 video.
Đang tự động tải file 'tiktok_data_xehơi.csv' xuống...

In [ ]:
#Tách lấy cột URL
import pandas as pd
from google.colab import files
import io

# 1. Tải file CSV lên từ máy tính
print("Hãy chọn file CSV bạn vừa tải xuống:")
uploaded = files.upload()

# 2. Đọc file vừa tải lên
for filename in uploaded.keys():
    df_imported = pd.read_csv(io.BytesIO(uploaded[filename]))

    # 3. Kiểm tra và lấy cột URL
    if 'URL' in df_imported.columns:
        url_column = df_imported[['URL']]
        print(f"\n--- Đã trích xuất cột URL từ file: {filename} ---")
        display(url_column)

        # 4. Lưu thành file mới và tự động tải về
        output_filename = f"extracted_urls_{filename}"
        url_column.to_csv(output_filename, index=False, encoding='utf-8-sig')

        print(f"Đang tự động tải file kết quả '{output_filename}' xuống...")
        files.download(output_filename)
    else:
        print(f"\n[LỖI] Không tìm thấy cột 'URL' trong file {filename}.")
        print("Các cột hiện có:", df_imported.columns.tolist())

Hãy chọn file CSV bạn vừa tải xuống:

Saving tiktok_data_xehơi.csv to tiktok_data_xehơi (1).csv

--- Đã trích xuất cột URL từ file: tiktok_data_xehơi (1).csv ---

                                                  URL
0   https://www.tiktok.com/@zoom6car/video/7613253...
1   https://www.tiktok.com/@anhchuxuongdeptrai/vid...
2   https://www.tiktok.com/@vungocthanhh/video/735...
3   https://www.tiktok.com/@quenha.6/video/7608966...
4   https://www.tiktok.com/@cuongnuocmy/video/7427...
5   https://www.tiktok.com/@cuongnuocmy/video/7377...
6   https://www.tiktok.com/@autocarclub/video/7275...
7   https://www.tiktok.com/@thaidacde1999/video/75...
8   https://www.tiktok.com/@sieuxe.360/video/76126...
9   https://www.tiktok.com/@gatgu_channel/video/74...
10  https://www.tiktok.com/@chuyen_ve_oto/video/76...
11  https://www.tiktok.com/@bnkn_tv2/video/7612907...
12  https://www.tiktok.com/@phukienxehoiplus/video...
13  https://www.tiktok.com/@hoarousy/video/7374754...
14  https://www.tiktok.com/@alexnguye/video/730651...
15  https://www.tiktok.com/@thuthuyyy99neee/video/...
16  https://www.tiktok.com/@hcar.vn/video/76128548...
17  https://www.tiktok.com/@vo_tran_quoc_trung/vid...
18  https://www.tiktok.com/@hiucar2010/video/74128...
19  https://www.tiktok.com/@memoe2609_/video/75843...

Đang tự động tải file kết quả 'extracted_urls_tiktok_data_xehơi (1).csv' xuống...

In [ ]:
#Tổng hợp công đoạn crawl
import pandas as pd
import requests
import re
import time
import random
from google.colab import files

def run_full_comment_crawl(target_df, comments_limit=30):
    all_comments_data = []
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Referer": "https://www.tiktok.com/"
    }

    # 1. Trích xuất URL
    if 'URL' not in target_df.columns:
        print("Lỗi: Không tìm thấy cột 'URL' trong dữ liệu.")
        return

    urls = target_df['URL'].tolist()
    print(f"Bắt đầu quét {len(urls)} video...")

    # 2. Duyệt qua từng URL và lấy Comment
    for i, url in enumerate(urls):
        try:
            match = re.search(r'video/(\d+)', url)
            if not match: continue
            video_id = match.group(1)

            print(f"[{i+1}/{len(urls)}] Đang lấy comment video ID: {video_id}...")
            api_url = f"https://www.tiktok.com/api/comment/list/?aid=1988&aweme_id={video_id}&count={comments_limit}&cursor=0"

            response = requests.get(api_url, headers=headers, timeout=15)

            if response.status_code == 200:
                data = response.json()
                comments = data.get('comments', [])

                for c in comments:
                    all_comments_data.append({
                        "Video ID": video_id,
                        "Comment Content": c.get("text", ""),
                        "User": c.get("user", {}).get("unique_id", ""),
                        "Like Count": c.get("digg_count", 0)
                    })
                print(f"  -> Thành công: Lấy được {len(comments)} bình luận.")
            else:
                print(f"  -> Thất bại: Mã lỗi {response.status_code}")

            # Nghỉ giữa các lần gọi để tránh bị chặn
            time.sleep(random.uniform(1.5, 3.0))

        except Exception as e:
            print(f"  -> Lỗi khi xử lý URL {url}: {e}")
            continue

    # 3. Xuất file và tải về
    if all_comments_data:
        df_result = pd.DataFrame(all_comments_data)
        output_name = "tiktok_all_comments.csv"
        df_result.to_csv(output_name, index=False, encoding='utf-8-sig')
        print(f"\n--- HOÀN THÀNH ---")
        print(f"Tổng số bình luận thu thập: {len(df_result)}")
        print(f"Đang tải file '{output_name}'...")
        files.download(output_name)
    else:
        print("\nKhông thu thập được bình luận nào.")

# Kiểm tra nếu biến df_imported (từ bước upload) tồn tại
if 'df_imported' in globals():
    run_full_comment_crawl(df_imported, comments_limit=30)
else:
    print("Vui lòng chạy ô 'Tải file CSV lên' trước khi thực hiện bước này.")

Bắt đầu quét 20 video...
[1/20] Đang lấy comment video ID: 7613253519184842005...
  -> Thành công: Lấy được 1 bình luận.
[2/20] Đang lấy comment video ID: 7612659344768896264...
  -> Thành công: Lấy được 3 bình luận.
[3/20] Đang lấy comment video ID: 7353136888313679124...
  -> Thành công: Lấy được 29 bình luận.
[4/20] Đang lấy comment video ID: 7608966011928317215...
  -> Thành công: Lấy được 28 bình luận.
[5/20] Đang lấy comment video ID: 7427307108728687915...
  -> Thành công: Lấy được 29 bình luận.
[6/20] Đang lấy comment video ID: 7377548592749317418...
  -> Thành công: Lấy được 29 bình luận.
[7/20] Đang lấy comment video ID: 7275932066582154503...
  -> Thành công: Lấy được 29 bình luận.
[8/20] Đang lấy comment video ID: 7544259066764479762...
  -> Thành công: Lấy được 28 bình luận.
[9/20] Đang lấy comment video ID: 7612687977428339975...
  -> Thành công: Lấy được 1 bình luận.
[10/20] Đang lấy comment video ID: 7456391235574517008...
  -> Thành công: Lấy được 30 bình luận.
[11/20] Đang lấy comment video ID: 7605222950781898004...
  -> Thành công: Lấy được 29 bình luận.
[12/20] Đang lấy comment video ID: 7612907193507138834...
  -> Thành công: Lấy được 2 bình luận.
[13/20] Đang lấy comment video ID: 7355697971394088210...
  -> Thành công: Lấy được 30 bình luận.
[14/20] Đang lấy comment video ID: 7374754620641430792...
  -> Thành công: Lấy được 29 bình luận.
[15/20] Đang lấy comment video ID: 7306514112425544961...
  -> Thành công: Lấy được 24 bình luận.
[16/20] Đang lấy comment video ID: 7612772155197050132...
  -> Thành công: Lấy được 2 bình luận.
[17/20] Đang lấy comment video ID: 7612854832122055944...
  -> Thành công: Lấy được 30 bình luận.
[18/20] Đang lấy comment video ID: 7613083016071597333...
  -> Thành công: Lấy được 2 bình luận.
[19/20] Đang lấy comment video ID: 7412855572627934470...
  -> Thành công: Lấy được 29 bình luận.
[20/20] Đang lấy comment video ID: 7584388044275453204...
  -> Thành công: Lấy được 30 bình luận.

--- HOÀN THÀNH ---
Tổng số bình luận thu thập: 414
Đang tải file 'tiktok_all_comments.csv'...

#**PHIÊN BẢN CẢI THIỆN**
- Chuẩn hóa keyword nhập đầu vào, chuyển thành hashtag

- Tìm kiếm dựa trên hagtash

- Lọc cột URL, tự động crawl comment dựa trên URL

- Chuẩn hóa comment loại bỏ icon, khoảng trống không cần thiết

In [10]:
#Cài đặt các thư viện cần thiết hỗ trợ crawl dữ liệu trên TikTok
!pip install TikTokApi
!pip install pandas

!playwright install
!playwright install-deps

Requirement already satisfied: TikTokApi in /usr/local/lib/python3.12/dist-packages (7.3.1)
Requirement already satisfied: requests<3.0,>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from TikTokApi) (2.32.4)
Requirement already satisfied: playwright<2.0,>=1.36.0 in /usr/local/lib/python3.12/dist-packages (from TikTokApi) (1.58.0)
Requirement already satisfied: httpx<1.0,>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from TikTokApi) (0.28.1)
Requirement already satisfied: proxyproviders<0.3.0,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from TikTokApi) (0.2.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.27.0->TikTokApi) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.27.0->TikTokApi) (0.16.0)
Requirement already satisfied: pyee<14,>=13 in /usr/local/lib/python3.12/dist-packages (from playwright<2.0,>=1.36.0->TikTokApi) (13.0.1)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from playwright<2.0,>=1.36.0->TikTokApi) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31.0->TikTokApi) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0,>=2.31.0->TikTokApi) (2.5.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from pyee<14,>=13->playwright<2.0,>=1.36.0->TikTokApi) (4.15.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 447, in run
    conflicts = self._determine_conflicts(to_install)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 578, in _determine_conflicts
    return check_install_conflicts(to_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 101, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 39, in create_package_set_from_installed
    for dist in env.iter_installed_distributions(local_only=False, skip=()):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/base.py", line 664, in <genexpr>
    return (d for d in it if d.canonical_name not in skip)
                       ^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions
    yield from finder.find(location)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find
    for dist, info_location in self._find_impl(location):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl
    raw_name = get_dist_name(dist)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name
    name = cast(Any, dist).name
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 457, in name
    return self.metadata['Name']
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 452, in metadata
    return _adapters.Message(email.message_from_string(text))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/__init__.py", line 37, in message_from_string
    return Parser(*args, **kws).parsestr(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/parser.py", line 64, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/parser.py", line 53, in parse
    feedparser.feed(data)
  File "/usr/lib/python3.12/email/feedparser.py", line 174, in feed
    self._call_parse()
  File "/usr/lib/python3.12/email/feedparser.py", line 178, in _call_parse
    self._parse()
  File "/usr/lib/python3.12/email/feedparser.py", line 222, in _parsegen
    for line in self._input:
                ^^^^^^^^^^^
  File "/usr/lib/python3.12/email/feedparser.py", line 128, in __next__
    line = self.readline()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/email/feedparser.py", line 88, in readline
    for ateof in reversed(self._eofstack):
                 ^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1022, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/logging.py", line 219, in filter
    def filter(self, record: logging.LogRecord) -> bool:

KeyboardInterrupt
^C

KeyboardInterrupt:

In [3]:
import asyncio
from TikTokApi import TikTokApi
import pandas as pd
from google.colab import files
import re
import unicodedata
from datetime import datetime


# ==============================
# 1. Chuẩn hóa keyword đầu vào
# ==============================
def normalize_keyword(keyword):

    keyword = keyword.strip().lower()

    # bỏ ký tự đặc biệt
    keyword = re.sub(r'[^\w\s]', '', keyword)

    # bỏ dấu tiếng Việt
    keyword = ''.join(
        c for c in unicodedata.normalize('NFD', keyword)
        if unicodedata.category(c) != 'Mn'
    )

    hashtag_name = keyword.replace(" ", "")

    return hashtag_name


# ==============================
# 2. Tạo session an toàn
# ==============================
async def create_session_safe(api):

    for attempt in range(3):
        try:
            await api.create_sessions(
                num_sessions=1,
                sleep_after=10,
                browser="webkit",
                headless=True
            )
            return
        except Exception as e:
            print(f"Lỗi tạo session (lần {attempt+1})")
            await asyncio.sleep(5)

    raise Exception("Không thể tạo session TikTok")


# ==============================
# 3. Crawl video theo hashtag
# ==============================
async def crawl_and_export_csv(keyword, video_count=10):

    hashtag_name = normalize_keyword(keyword)

    print(f"Đang tìm kiếm hashtag: #{hashtag_name}")

    api = TikTokApi()
    video_data_list = []

    try:

        await create_session_safe(api)

        tag = api.hashtag(name=hashtag_name)

        count = 0

        print("Đang thu thập dữ liệu...")

        async for video in tag.videos(count=video_count):

            try:

                v_info = video.as_dict

                author = v_info.get("author", {}).get("uniqueId")
                v_id = v_info.get("id")

                # bỏ video thiếu dữ liệu
                if not author or not v_id:
                    continue

                stats = v_info.get("stats", {})

                video_url = f"https://www.tiktok.com/@{author}/video/{v_id}"

                record = {

                    "Video ID": v_id,

                    "Video URL": video_url,

                    "Tác giả": author,

                    "Mô tả": v_info.get("desc", ""),

                    "Thời gian đăng": v_info.get("createTime"),

                    "Thời lượng": v_info.get("video", {}).get("duration", 0),

                    "Lượt tim": stats.get("diggCount", 0),

                    "Lượt xem": stats.get("playCount", 0),

                    "Lượt chia sẻ": stats.get("shareCount", 0),

                    "Lượt bình luận": stats.get("commentCount", 0),

                    "Hashtag": hashtag_name
                }

                video_data_list.append(record)

                print(f"[{count+1}/{video_count}] {video_url}")

                count += 1

                if count >= video_count:
                    break

                await asyncio.sleep(1)

            except Exception as e:
                print("Lỗi khi xử lý video:", e)
                continue

        if video_data_list:

            df = pd.DataFrame(video_data_list)

            # loại bỏ trùng
            df = df.drop_duplicates(subset="Video ID")

            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

            csv_filename = f"tiktok_data_{hashtag_name}_{timestamp}.csv"

            df.to_csv(
                csv_filename,
                index=False,
                encoding="utf-8-sig"
            )

            print("\n[XONG] Đã thu thập", len(df), "video")
            print("Đang tải file CSV...")

            files.download(csv_filename)

        else:
            print("Không có dữ liệu (có thể bị TikTok chặn).")

    except Exception as e:
        print("Lỗi:", e)

    finally:
        await api.close_sessions()


# ==============================
# 4. Cấu hình chạy
# ==============================

keyword = "du lịch %&^*^"  # @param {type:"string"}

video_limit = 30  # @param {type:"integer"}

await crawl_and_export_csv(keyword, video_count=video_limit)

Đang tìm kiếm hashtag: #dulich
Đang thu thập dữ liệu...
[1/30] https://www.tiktok.com/@thuykieu_2802/video/7589906430824795399
[2/30] https://www.tiktok.com/@thuykieu_2802/video/7535780207366704391
[3/30] https://www.tiktok.com/@phuongtrip11/video/7513501547175873800
[4/30] https://www.tiktok.com/@kaiph__/video/7365128711143902482
[5/30] https://www.tiktok.com/@sau5894/video/7558108154458819848
[6/30] https://www.tiktok.com/@zavatravel/video/7277304545565232392
[7/30] https://www.tiktok.com/@bunchaiue/video/7591781896086998292
[8/30] https://www.tiktok.com/@minhhang_buingoc/video/7276089385718762753
[9/30] https://www.tiktok.com/@kid_2509/video/7412277687949085959
[10/30] https://www.tiktok.com/@gowith_we/video/7410631152202943745
[11/30] https://www.tiktok.com/@zavatravel/video/7289118632284654856
[12/30] https://www.tiktok.com/@gowith_we/video/7491660880023670034
[13/30] https://www.tiktok.com/@trangg1423/video/7576105755024149767
[14/30] https://www.tiktok.com/@pupu.haha/video/7604385762389413140
[15/30] https://www.tiktok.com/@yeutiengthai/video/7280720171113712897
[16/30] https://www.tiktok.com/@volethuytrinh/video/7162559333165731098
[17/30] https://www.tiktok.com/@resortnhatrang/video/7319850414491421954
[18/30] https://www.tiktok.com/@suoimopark/video/7565486111607262471
[19/30] https://www.tiktok.com/@crystalbay.24/video/7500887500030741768
[20/30] https://www.tiktok.com/@vtthaoo/video/7403963345176415504
[21/30] https://www.tiktok.com/@vtthaoo/video/7612503603441388807
[22/30] https://www.tiktok.com/@yeusapa24/video/7608909069763595538
[23/30] https://www.tiktok.com/@capcut_dungxuhue/video/7411164293988650241
[24/30] https://www.tiktok.com/@nhiclouday/video/7589880811378232597
[25/30] https://www.tiktok.com/@nphlinhhhh/video/7520565184889408784
[26/30] https://www.tiktok.com/@dulich.lgbt/video/7613177075947834632
[27/30] https://www.tiktok.com/@hiendulichngoisao/video/7569851969527926023
[28/30] https://www.tiktok.com/@vtthaoo/video/7503776240025865480
[29/30] https://www.tiktok.com/@vtthaoo/video/7570944304596716820
[30/30] https://www.tiktok.com/@junenarakk/video/7484493254252137735

[XONG] Đã thu thập 30 video
Đang tải file CSV...

In [5]:
#Tách lấy cột Video URL
import pandas as pd
from google.colab import files
import io

# 1. Tải file CSV lên từ máy tính
print("Hãy chọn file CSV bạn vừa tải xuống:")
uploaded = files.upload()

# 2. Đọc file vừa tải lên
for filename in uploaded.keys():
    df_imported = pd.read_csv(io.BytesIO(uploaded[filename]))

    # 3. Kiểm tra và lấy cột URL
    if 'URL' in df_imported.columns:
        url_column = df_imported[['Video URL']]
        print(f"\n--- Đã trích xuất cột URL từ file: {filename} ---")
        display(url_column)

        # 4. Lưu thành file mới và tự động tải về
        output_filename = f"extracted_urls_{filename}"
        url_column.to_csv(output_filename, index=False, encoding='utf-8-sig')

        print(f"Đang tự động tải file kết quả '{output_filename}' xuống...")
        files.download(output_filename)
    else:
        print(f"\n[LỖI] Không tìm thấy cột 'URL' trong file {filename}.")
        print("Các cột hiện có:", df_imported.columns.tolist())

Hãy chọn file CSV bạn vừa tải xuống:

Saving tiktok_data_dulich_20260306_005750.csv to tiktok_data_dulich_20260306_005750 (2).csv

[LỖI] Không tìm thấy cột 'URL' trong file tiktok_data_dulich_20260306_005750 (2).csv.
Các cột hiện có: ['Video ID', 'Video URL', 'Tác giả', 'Mô tả', 'Thời gian đăng', 'Thời lượng', 'Lượt tim', 'Lượt xem', 'Lượt chia sẻ', 'Lượt bình luận', 'Hashtag']

In [6]:
import pandas as pd
from google.colab import files
import io

# 1. Upload file CSV
print("Hãy chọn file CSV do crawler TikTok tạo:")
uploaded = files.upload()

# 2. Đọc file CSV
for filename in uploaded.keys():

    df_imported = pd.read_csv(io.BytesIO(uploaded[filename]))

    # 3. Kiểm tra cột Video URL
    if 'Video URL' in df_imported.columns:

        url_column = df_imported[['Video URL']].copy()

        # chuẩn hóa URL
        url_column['Video URL'] = url_column['Video URL'].astype(str).str.strip()

        # loại bỏ dòng rỗng
        url_column = url_column[url_column['Video URL'] != ""]

        print(f"\n--- Đã trích xuất cột Video URL từ file: {filename} ---")
        display(url_column)

        # 4. Lưu file mới
        output_filename = f"extracted_video_urls_{filename}"

        url_column.to_csv(
            output_filename,
            index=False,
            encoding='utf-8-sig'
        )

        print(f"Đang tải file kết quả '{output_filename}' xuống...")

        files.download(output_filename)

    else:

        print(f"\n[LỖI] Không tìm thấy cột 'Video URL' trong file {filename}")
        print("Các cột hiện có:", df_imported.columns.tolist())

Hãy chọn file CSV do crawler TikTok tạo:

Saving tiktok_data_dulich_20260306_005750.csv to tiktok_data_dulich_20260306_005750 (3).csv

--- Đã trích xuất cột Video URL từ file: tiktok_data_dulich_20260306_005750 (3).csv ---

                                            Video URL
0   https://www.tiktok.com/@thuykieu_2802/video/75...
1   https://www.tiktok.com/@thuykieu_2802/video/75...
2   https://www.tiktok.com/@phuongtrip11/video/751...
3   https://www.tiktok.com/@kaiph__/video/73651287...
4   https://www.tiktok.com/@sau5894/video/75581081...
5   https://www.tiktok.com/@zavatravel/video/72773...
6   https://www.tiktok.com/@bunchaiue/video/759178...
7   https://www.tiktok.com/@minhhang_buingoc/video...
8   https://www.tiktok.com/@kid_2509/video/7412277...
9   https://www.tiktok.com/@gowith_we/video/741063...
10  https://www.tiktok.com/@zavatravel/video/72891...
11  https://www.tiktok.com/@gowith_we/video/749166...
12  https://www.tiktok.com/@trangg1423/video/75761...
13  https://www.tiktok.com/@pupu.haha/video/760438...
14  https://www.tiktok.com/@yeutiengthai/video/728...
15  https://www.tiktok.com/@volethuytrinh/video/71...
16  https://www.tiktok.com/@resortnhatrang/video/7...
17  https://www.tiktok.com/@suoimopark/video/75654...
18  https://www.tiktok.com/@crystalbay.24/video/75...
19  https://www.tiktok.com/@vtthaoo/video/74039633...
20  https://www.tiktok.com/@vtthaoo/video/76125036...
21  https://www.tiktok.com/@yeusapa24/video/760890...
22  https://www.tiktok.com/@capcut_dungxuhue/video...
23  https://www.tiktok.com/@nhiclouday/video/75898...
24  https://www.tiktok.com/@nphlinhhhh/video/75205...
25  https://www.tiktok.com/@dulich.lgbt/video/7613...
26  https://www.tiktok.com/@hiendulichngoisao/vide...
27  https://www.tiktok.com/@vtthaoo/video/75037762...
28  https://www.tiktok.com/@vtthaoo/video/75709443...
29  https://www.tiktok.com/@junenarakk/video/74844...

Đang tải file kết quả 'extracted_video_urls_tiktok_data_dulich_20260306_005750 (3).csv' xuống...

In [7]:
import pandas as pd
import requests
import re
import time
import random
from google.colab import files

def run_full_comment_crawl(target_df, comments_limit=30):

    all_comments_data = []

    headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": "https://www.tiktok.com/"
    }

    # =============================
    # 1. Xác định cột URL
    # =============================

    if 'Video URL' in target_df.columns:
        url_column = 'Video URL'

    elif 'URL' in target_df.columns:
        url_column = 'URL'

    else:
        print("Lỗi: Không tìm thấy cột URL trong dữ liệu")
        print("Các cột hiện có:", target_df.columns.tolist())
        return


    urls = target_df[url_column].dropna().tolist()

    print(f"Bắt đầu quét {len(urls)} video...")


    # =============================
    # 2. Crawl comment từng video
    # =============================

    for i, url in enumerate(urls):

        try:

            url = str(url).strip()

            match = re.search(r'video/(\d+)', url)

            if not match:
                print("  -> Không lấy được video_id")
                continue

            video_id = match.group(1)

            print(f"[{i+1}/{len(urls)}] Video ID: {video_id}")

            api_url = f"https://www.tiktok.com/api/comment/list/?aid=1988&aweme_id={video_id}&count={comments_limit}&cursor=0"

            response = requests.get(api_url, headers=headers, timeout=15)

            if response.status_code == 200:

                data = response.json()

                comments = data.get("comments", [])

                print(f"  -> Lấy được {len(comments)} comment")

                for c in comments:

                    all_comments_data.append({

                        "Video ID": video_id,

                        "Video URL": url,

                        "Comment Content": c.get("text", ""),

                        "User": c.get("user", {}).get("unique_id", ""),

                        "Like Count": c.get("digg_count", 0)

                    })

            else:

                print(f"  -> Lỗi HTTP {response.status_code}")


            time.sleep(random.uniform(1.5, 3.5))


        except Exception as e:

            print(f"  -> Lỗi khi xử lý URL {url}: {e}")

            continue


    # =============================
    # 3. Xuất CSV
    # =============================

    if all_comments_data:

        df_result = pd.DataFrame(all_comments_data)

        output_name = "tiktok_all_comments.csv"

        df_result.to_csv(

            output_name,
            index=False,
            encoding='utf-8-sig'
        )

        print("\n--- HOÀN THÀNH ---")

        print("Tổng số comment:", len(df_result))

        files.download(output_name)

    else:

        print("\nKhông thu thập được comment nào.")



# =============================
# 4. Chạy crawler
# =============================

if 'df_imported' in globals():

    run_full_comment_crawl(df_imported, comments_limit=30)

else:

    print("Vui lòng chạy bước upload CSV trước.")

Bắt đầu quét 30 video...
[1/30] Video ID: 7589906430824795399
  -> Lấy được 30 comment
[2/30] Video ID: 7535780207366704391
  -> Lấy được 29 comment
[3/30] Video ID: 7513501547175873800
  -> Lấy được 30 comment
[4/30] Video ID: 7365128711143902482
  -> Lấy được 30 comment
[5/30] Video ID: 7558108154458819848
  -> Lấy được 20 comment
[6/30] Video ID: 7277304545565232392
  -> Lấy được 30 comment
[7/30] Video ID: 7591781896086998292
  -> Lấy được 30 comment
[8/30] Video ID: 7276089385718762753
  -> Lấy được 30 comment
[9/30] Video ID: 7412277687949085959
  -> Lấy được 30 comment
[10/30] Video ID: 7410631152202943745
  -> Lấy được 30 comment
[11/30] Video ID: 7289118632284654856
  -> Lấy được 29 comment
[12/30] Video ID: 7491660880023670034
  -> Lấy được 30 comment
[13/30] Video ID: 7576105755024149767
  -> Lấy được 30 comment
[14/30] Video ID: 7604385762389413140
  -> Lấy được 30 comment
[15/30] Video ID: 7280720171113712897
  -> Lấy được 30 comment
[16/30] Video ID: 7162559333165731098
  -> Lấy được 30 comment
[17/30] Video ID: 7319850414491421954
  -> Lấy được 30 comment
[18/30] Video ID: 7565486111607262471
  -> Lấy được 30 comment
[19/30] Video ID: 7500887500030741768
  -> Lấy được 30 comment
[20/30] Video ID: 7403963345176415504
  -> Lấy được 30 comment
[21/30] Video ID: 7612503603441388807
  -> Lấy được 29 comment
[22/30] Video ID: 7608909069763595538
  -> Lấy được 21 comment
[23/30] Video ID: 7411164293988650241
  -> Lấy được 15 comment
[24/30] Video ID: 7589880811378232597
  -> Lấy được 30 comment
[25/30] Video ID: 7520565184889408784
  -> Lấy được 30 comment
[26/30] Video ID: 7613177075947834632
  -> Lấy được 30 comment
[27/30] Video ID: 7569851969527926023
  -> Lấy được 30 comment
[28/30] Video ID: 7503776240025865480
  -> Lấy được 30 comment
[29/30] Video ID: 7570944304596716820
  -> Lấy được 30 comment
[30/30] Video ID: 7484493254252137735
  -> Lấy được 25 comment

--- HOÀN THÀNH ---
Tổng số comment: 858

In [9]:
import pandas as pd
import re
from google.colab import files
import io

print("Hãy chọn file CSV comment:")
uploaded = files.upload()

# =============================
# Hàm xoá được nhiều emoji trong comment hơn
# =============================

def remove_emoji(text):

    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F700-\U0001F77F"
        "\U0001F780-\U0001F7FF"
        "\U0001F800-\U0001F8FF"
        "\U0001F900-\U0001F9FF"
        "\U0001FA00-\U0001FAFF"
        "\U00002600-\U000026FF"
        "\U00002700-\U000027BF"
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub("", text)


# =============================
# Chuẩn hoá comment
# =============================

def normalize_comment(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # xoá emoji
    text = remove_emoji(text)

    # xoá xuống dòng
    text = text.replace("\n", " ")

    # xoá khoảng trắng dư
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# =============================
# Xử lý file
# =============================

for filename in uploaded.keys():

    df = pd.read_csv(io.BytesIO(uploaded[filename]))

    if "Comment Content" not in df.columns:

        print("Không tìm thấy cột 'Comment Content'")
        print("Các cột hiện có:", df.columns.tolist())

    else:

        print("Bắt đầu chuẩn hoá comment...")

        df["Comment Clean"] = df["Comment Content"].apply(normalize_comment)

        # xoá comment rỗng
        df = df[df["Comment Clean"] != ""]

        print("Số comment sau khi làm sạch:", len(df))

        output_file = "tiktok_comments_cleaned.csv"

        df.to_csv(
            output_file,
            index=False,
            encoding="utf-8-sig"
        )

        print("Đã hoàn thành chuẩn hoá!")

        files.download(output_file)

Hãy chọn file CSV comment:

Saving tiktok_all_comments (3).csv to tiktok_all_comments (3) (1).csv
Bắt đầu chuẩn hoá comment...
Số comment sau khi làm sạch: 810
Đã hoàn thành chuẩn hoá!